POS/POS.Web/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.ViewModel;
using POS.Service;

namespace POS.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeService _service;
        public EmployeeController(AppDbContext context) 
        {
            _service = new EmployeeService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var data = _service.GetEmployee();
            return View(data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AddModal()
        {
            return View("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(EmployeeModel request) 
        {
            if (ModelState.IsValid)
            {
                _service.AddEmployee(new EmployeeEntity(request));
                return Redirect("/Employee");
            }
            return View("Add", request);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var data = _service.DetailEmployee(id);
            return View(data);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(EmployeeModel employee)
        {
            if (ModelState.IsValid)
            {
                _service.UpdateEmployee(employee);
                return Redirect("/Employee");

            }
            return View("Edit", employee);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.DeleteEmployee(id);
            return Redirect("/Employee");
        }

    }
}

POS/POS.Web/Views/Employee/Add.cshtml
@model POS.ViewModel.EmployeeModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Employee";
}
<h2>Add Employee</h2>

<form asp-controller="Employee" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="TitleOfCourtesy"></label>
        <input asp-for="TitleOfCourtesy" class="form-control" />
        <span asp-validation-for="TitleOfCourtesy" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="BirthDate"></label>
        <input asp-for="BirthDate" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="HireDate"></label>
        <input asp-for="HireDate" class="form-control" />
        <span asp-validation-for="HireDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Extension"></label>
        <input asp-for="Extension" class="form-control" />
        <span asp-validation-for="Extension" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="HomePhone"></label>
        <input asp-for="HomePhone" class="form-control" />
        <span asp-validation-for="HomePhone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Notes"></label>
        <input asp-for="Notes" class="form-control" />
        <span asp-validation-for="Notes" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ReportTo"></label>
        <input asp-for="ReportTo" class="form-control" />
        <span asp-validation-for="ReportTo" class="text-danger" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Employee/Details.cshtml
@model POS.Repository.EmployeeEntity
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Detail Employe";
}
<h2>Detail Employe</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Last Name</th>
        <td>@Model.LastName</td>
    </tr>
    <tr>
        <th>First Name</th>
        <td>@Model.FirstName</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>@Model.Title</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>@Model.TitleOfCourtesy</td>
    </tr>
     <tr>
        <th>Title</th>
        <td>@Model.BirthDate</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>@Model.HireDate</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <th>City</th>
        <td>@Model.City</td>
    </tr>
    <tr>
        <th>region</th>
        <td>@Model.region</td>
    </tr>
    <tr>
        <th>PostalCode</th>
        <td>@Model.PostalCode</td>
    </tr>
    <tr>
        <th>Country</th>
        <td>@Model.Country</td>
    </tr>
    <tr>
        <th>Home Phone</th>
        <td>@Model.HomePhone</td>
    </tr>
    <tr>
        <th>Extension</th>
        <td>@Model.Extension</td>
    </tr>
     <tr>
        <th>Notes</th>
        <td>@Model.Notes</td>
    </tr>
     <tr>
        <th>ReportTo</th>
        <td>@Model.ReportTo</td>
    </tr>
</table>

POS/POS.Web/Views/Employee/Edit.cshtml
@model POS.ViewModel.EmployeeModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Employe";
}
<h2>Edit Employee</h2>
<form asp-controller="Employee" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="TitleOfCourtesy"></label>
        <input asp-for="TitleOfCourtesy" class="form-control" />
        <span asp-validation-for="TitleOfCourtesy" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="BirthDate"></label>
        <input asp-for="BirthDate" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="HireDate"></label>
        <input asp-for="HireDate" class="form-control" />
        <span asp-validation-for="HireDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Extension"></label>
        <input asp-for="Extension" class="form-control" />
        <span asp-validation-for="Extension" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="HomePhone"></label>
        <input asp-for="HomePhone" class="form-control" />
        <span asp-validation-for="HomePhone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Notes"></label>
        <input asp-for="Notes" class="form-control" />
        <span asp-validation-for="Notes" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ReportTo"></label>
        <input asp-for="ReportTo" class="form-control" />
        <span asp-validation-for="ReportTo" class="text-danger" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Employee/Index.cshtml
@model IEnumerable<POS.Repository.EmployeeEntity>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Employee List";
}

<h2>EMployee List</h2>
<a id="btn-add" class="btn btn-primary" asp-area="" asp-controller="Employee" asp-action="Add">Add Employee</a>
<table class="table table-responsive">
    <thead>
    <th>Id</th>
    <th>Name</th>
    <th>Title</th>
    <th>Birth Date</th>
    <th>Hire Date</th>
    <th>Homephone Number</th>

    <th>Action</th>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
        <td>@item.Id</td>
        <td>>@item.FirstName, @item.LastName</td>
        <td>@item.Title</td>
        <td>@item.BirthDate</td>
        <td>@item.HireDate</td>
        <td>@item.HomePhone</td>>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
        </td>
        </tbody>
    }
</table>

<div id="my-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#btn-add").on("click", function(e){
            e.preventDefault();
            $.ajax({
                url:"Customer/AddModal",
                type:"GET",
                dataType:"html",
                success: function(data){
                    $("#my-modal").find(".modal-body").html(data);
                    $("#my-modal").modal("show");
                }
            });
        });
    </script>
}

POS/POS.Web/Views/Employee/_Add.cshtml
@model POS.ViewModel.EmployeeModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Employee";
}
<h2>Add Employee</h2>

<form asp-controller="Employee" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="TitleOfCourtesy"></label>
        <input asp-for="TitleOfCourtesy" class="form-control" />
        <span asp-validation-for="TitleOfCourtesy" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="BirthDate"></label>
        <input asp-for="BirthDate" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="HireDate"></label>
        <input asp-for="HireDate" class="form-control" />
        <span asp-validation-for="HireDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Extension"></label>
        <input asp-for="Extension" class="form-control" />
        <span asp-validation-for="Extension" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="HomePhone"></label>
        <input asp-for="HomePhone" class="form-control" />
        <span asp-validation-for="HomePhone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Notes"></label>
        <input asp-for="Notes" class="form-control" />
        <span asp-validation-for="Notes" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ReportTo"></label>
        <input asp-for="ReportTo" class="form-control" />
        <span asp-validation-for="ReportTo" class="text-danger" />
    </div>
    <<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}