POS/POS.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderService _service;
        private readonly CustomerService _serviceCus;
        private readonly EmployeeService _serviceEmp;
        private readonly ProductService _servicePrd;

        public OrderController(AppDbContext context) 
        {
            _service = new OrderService(context);
            _serviceCus = new CustomerService(context);
            _serviceEmp = new EmployeeService(context);           
            _servicePrd = new ProductService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var data = _service.GetOrders();
            return View(data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Customer = new SelectList(_serviceCus.GetCustomer(), "Id", "ContactName");
            ViewBag.Employee = new SelectList(_serviceEmp.GetEmployee(), "Id", "FirstName");
            ViewBag.Product = new SelectList(_servicePrd.GetProducts(), "Id", "Name");
            return View();
        }

        [HttpGet]
        public IActionResult AddModal()
        {
            ViewBag.Customer = new SelectList(_serviceCus.GetCustomer(), "Id", "ContactName");
            ViewBag.Employee = new SelectList(_serviceEmp.GetEmployee(), "Id", "FirstName");
            ViewBag.Product = new SelectList(_servicePrd.GetProducts(), "Id", "Name");
            return View("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("CustomerId, EmployeeId, OrderDate, RequiredDate, ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry, OrderDetails")] OrderModel request)
        {
            if (ModelState.IsValid)
            {
                _service.AddOrder(request);
                return Redirect("Index");
            }
            return View("Add", request);
        }


        [HttpGet]
        public IActionResult Details(int? id)
        {
            var data = _service.DetailOrder(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Invoice(int? id)
        {
            var data = _service.DetailInvoice(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.Customer = new SelectList(_serviceCus.GetCustomer(), "Id", "ContactName");
            ViewBag.Employee = new SelectList(_serviceEmp.GetEmployee(), "Id", "FirstName");
            var data = _service.DetailOrder(id);
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("CustomerId, EmployeeId, OrderDate, RequiredDate, ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry, OrderDetails")] OrderModel order)
        {
            if( ModelState.IsValid)
            {
                _service.UpdateOrder(order);
                return Redirect("/Order");
            }
            return View("Edit", order);
        }


        [HttpGet]

        public IActionResult Delete(int? id)
        {
            _service.DeleteOrder(id);
            return Redirect("/Order");
        }


    }
}

POS/POS.Web/Views/Order/Add.cshtml
@model POS.ViewModel.OrderModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Order";
}
<h2>Add Order</h2>

<form asp-controller="Order" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CustomerId">Customer ID</label>
        <select type="text" asp-for="CustomerId" class="form-control" asp-items="@ViewBag.Customer">
            <option selected>Select Customer</option>
        </select>
        <span asp-validation-for="CustomerId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="EmployeeId">Employee ID</label>
       
        <select type="text" asp-for="EmployeeId" class="form-control" asp-items="@ViewBag.Employee">
            <option selected>Select Employee</option>
        </select>
        <span asp-validation-for="EmployeeId" class="text-danger" />
    </div> 

    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="OrderDate"></label>
        <input asp-for="OrderDate" class="form-control" type="date"/>
        <span asp-validation-for="OrderDate" class="text-danger" />
    </div>

    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="RequiredDate"></label>
        <input asp-for="RequiredDate" class="form-control" type="date"/>
        <span asp-validation-for="RequiredDate" class="text-danger" />
    </div>
    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="ShippedDate"></label>
        <input asp-for="ShippedDate" class="form-control"  type="date"/>
        <span asp-validation-for="ShippedDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipVia"></label>
        <input asp-for="ShipVia" class="form-control" />
        <span asp-validation-for="ShipVia" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Freight"></label>
        <input asp-for="Freight" class="form-control" />
        <span asp-validation-for="Freight" class="text-danger" />
    </div>  
    <div class="form-group">
        <label asp-for="ShipName"></label>
        <input asp-for="ShipName" class="form-control" />
        <span asp-validation-for="ShipName" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipAddress"></label>
        <input asp-for="ShipAddress" class="form-control" />
        <span asp-validation-for="ShipAddress" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipCity"></label>
        <input asp-for="ShipCity" class="form-control" />
        <span asp-validation-for="ShipCity" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipRegion"></label>
        <input asp-for="ShipRegion" class="form-control" />
        <span asp-validation-for="ShipRegion" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipPostal"></label>
        <input asp-for="ShipPostal" class="form-control" />
        <span asp-validation-for="ShipPostal" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipCountry"></label>
        <input asp-for="ShipCountry" class="form-control" />
        <span asp-validation-for="ShipCountry" class="text-danger" />
    </div>
  
    <h2 class="content-caption mb-0 d-flex justify-content-between">
        Order Detail
        <a class="btn-add add-detail" data-added="0"><i class="la la-plus la-lg">+</i></a>
    </h2>

    <table class="table table-borderless m-0" id="tbl_posts2">
        <thead>
            <tr>
                <th>Product Id</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Discount</th>
            </tr>
        </thead>
        <tbody id="tbl_posts_body2">
            <tr id="re-0">
                <td>
                   @* <select type="text" asp-for="OrderDetails[0].ProductId" class="form-control" asp-items="@ViewBag.Product">
                        <option selected>Select the Product</option>
                    </select>*@
                    <input asp-for="OrderDetails[0].ProductId" class="form-control" />
                </td>
                </td>
                <td><input asp-for="OrderDetails[0].Price" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Quantity" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Discount" class="form-control" /></td>
                <td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td>
            </tr>

        </tbody>
        <tbody id="Detail-2">
        </tbody>

    </table>

    <div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

@*
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>*@



</form>

@section Scripts {
  <script type="text/javascript">
        $(document).ready(function () {

     
            var j = 1;
          
            $('a.add-detail').click(function () {
                $("#Detail-2").append('<tr><td><input id="OrderDetails_' + j + '__ProductId" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].ProductId" value=""/></td><td><input id="OrderDetails_' + j + '__Price" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Price" value=""/></td><td><input id="OrderDetails_' + j + '__Quantity" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Quantity" value=""/></td><td><input id="OrderDetails_' + j + '__Discount" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Discount" value=""/></td><td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td></tr>');
                j++;
            });
            $('#Detail-2').on('click', '.delete-detail', function () {
                $(this).parent().parent().remove();
                j--; 
                resetValues(); 
            });

            function resetValues() {
                counter = 1; 
                $("#Detail-2 tr").each(function () {
                   
                    $(this).find('.ProductId').attr("OrderDetails[" + counter + "].ProductId");
                    $(this).find('.Price').attr("OrderDetails[" + counter + "].Price");
                    $(this).find('.Quantity').attr("OrderDetails[" + counter + "].Quantity");
                    $(this).find('.Discount').attr("OrderDetails[" + counter + "].Discount");
                    counter++;
                })
            }
        });
    </script>

      
}

POS/POS.Web/Views/Order/Details.cshtml
@model POS.Repository.OrderEntity
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Detail Order";
}
<h2>Detail Order</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Customer Id</th>
        <td>@Model.CustomerId</td>
    </tr>
    <tr>
        <th>Employee id</th>
        <td>@Model.EmployeeId</td>
    </tr>
    <tr>
        <th>Order Date</th>
        <td>@Model.OrderDate</td>
    </tr>
    <tr>
        <th>Required Date</th>
        <td>@Model.RequiredDate</td>
    </tr>
    <tr>
        <th>Shipped Date</th>
        <td>@Model.ShippedDate</td>
    </tr>
    <tr>
        <th>Ship Via</th>
        <td>@Model.ShipVia</td>
    </tr>
    <tr>
        <th>Freight</th>
        <td>@Model.Freight</td>
    </tr>
    <tr>
        <th>Ship Name</th>
        <td>@Model.ShipName</td>
    </tr>
    <tr>
        <th>Ship Address</th>
        <td>@Model.ShipAddress</td>
    </tr>
     <tr>
        <th>Ship City</th>
        <td>@Model.ShipCity</td>
    </tr>
     <tr>
        <th>Ship Region</th>
        <td>@Model.ShipRegion</td>
    </tr>
     <tr>
        <th>Ship Postal</th>
        <td>@Model.ShipPostal</td>
    </tr>
     <tr>
        <th>Ship Country</th>
        <td>@Model.ShipCountry</td>
    </tr>

</table>

POS/POS.Web/Views/Order/Edit.cshtml
@model POS.ViewModel.OrderModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Order";
}
<h2>Edit Order</h2>
<form asp-controller="Order" asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control"  />
        <span asp-validation-for="Id" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="CustomerId">Customer ID</label>
        <select type="text" asp-for="CustomerId" class="form-control" asp-items="@ViewBag.Customer">
            <option selected>Select Customer</option>
        </select>
        <span asp-validation-for="CustomerId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="EmployeeId">Employee ID</label>

        <select type="text" asp-for="EmployeeId" class="form-control" asp-items="@ViewBag.Employee">
            <option selected>Select Employee</option>
        </select>
        <span asp-validation-for="EmployeeId" class="text-danger" />
    </div>

    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="OrderDate"></label>
        <input asp-for="OrderDate" class="form-control" type="date" />
        <span asp-validation-for="OrderDate" class="text-danger" />
    </div>

    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="RequiredDate"></label>
        <input asp-for="RequiredDate" class="form-control" type="date" />
        <span asp-validation-for="RequiredDate" class="text-danger" />
    </div>
    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="ShippedDate"></label>
        <input asp-for="ShippedDate" class="form-control" type="date" />
        <span asp-validation-for="ShippedDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipVia"></label>
        <input asp-for="ShipVia" class="form-control" />
        <span asp-validation-for="ShipVia" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Freight"></label>
        <input asp-for="Freight" class="form-control" />
        <span asp-validation-for="Freight" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipName"></label>
        <input asp-for="ShipName" class="form-control" />
        <span asp-validation-for="ShipName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipAddress"></label>
        <input asp-for="ShipAddress" class="form-control" />
        <span asp-validation-for="ShipAddress" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipCity"></label>
        <input asp-for="ShipCity" class="form-control" />
        <span asp-validation-for="ShipCity" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipRegion"></label>
        <input asp-for="ShipRegion" class="form-control" />
        <span asp-validation-for="ShipRegion" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipPostal"></label>
        <input asp-for="ShipPostal" class="form-control" />
        <span asp-validation-for="ShipPostal" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipCountry"></label>
        <input asp-for="ShipCountry" class="form-control" />
        <span asp-validation-for="ShipCountry" class="text-danger" />
    </div>

    <h2 class="content-caption mb-0 d-flex justify-content-between">
        Order Detail
        <a class="btn-add add-detail" data-added="0"><i class="la la-plus la-lg">+</i></a>
    </h2>

    <table class="table table-borderless m-0" id="tbl_posts2">
        <thead>
            <tr>
                <th>Product ID</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Discount</th>
            </tr>
        </thead>
        <tbody id="tbl_posts_body2">
            <tr id="re-0">
                <td>
                    <select type="text" asp-for="OrderDetails[0].ProductId" class="form-control" asp-items="@ViewBag.Product">
                        <option selected>Select the Product</option>
                    </select>
                </td>
                <td><input asp-for="OrderDetails[0].Price" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Quantity" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Discount" class="form-control" /></td>
                <td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td>
            </tr>

        </tbody>
        <tbody id="Detail-2">
        </tbody>

    </table>

    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

@section Scripts {
    
    <script type="text/javascript">



        $(document).ready(function () {
            var j = 1;
            $('a.add-detail').click(function () {
                $("#Detail-2").append('<tr><td><input id="OrderDetails_' + j + '__ProductId" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].ProductId" value=""/></td><td><input id="OrderDetails_' + j + '__Price" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Price" value=""/></td><td><input id="OrderDetails_' + j + '__Quantity" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Quantity" value=""/></td><td><input id="OrderDetails_' + j + '__Discount" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Discount" value=""/></td><td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td></tr>');
                j++;
            });
            $('#Detail-2').on('click', '.delete-detail', function () {
                $(this).parent().parent().remove();
                j--;
                resetValues();
            });
            function resetValues() {
                counter = 1;
                $("#Detail-2 tr").each(function () {
                    $(this).find('.ProductId').attr("OrderDetails[" + counter + "].ProductId");
                    $(this).find('.Price').attr("OrderDetails[" + counter + "].Price");
                    $(this).find('.Quantity').attr("OrderDetails[" + counter + "].Quantity");
                    $(this).find('.Discount').attr("OrderDetails[" + counter + "].Discount");
                    counter++;
                })
            }
        });


    </script>
}

POS/POS.Web/Views/Order/Index.cshtml
@model IEnumerable<POS.Repository.OrderEntity>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Order List";
}

<h2>Order List</h2>
<a id="btn-add" class="btn btn-primary" role="button" asp-area="" asp-controller="Order" asp-action="Add">Add Order</a>
<table class="table table-responsive">
    <thead>
    <th>Id</th>
    <th>Customer</th>
    <th>Employee</th>
    <th>Order Date</th>
    <th>Required Date</th>
    <th>Ship Date</th>
    <th>Ship Name</th>
    <th>Action</th>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
        <td>@item.Id</td>
        <td>@item.CustomerId</td>
        <td>@item.EmployeeId</td>
        <td>@item.OrderDate</td>
        <td>@item.RequiredDate</td>
        <td>@item.ShippedDate</td>
        <td>@item.ShipName</td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
            <a asp-action="Invoice" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
        </td>
        </tbody>
    }
</table>
<div id="my-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#btn-add").on("click", function(e){
        e.preventDefault();
        $.ajax({
        url:"Order/AddModal",
        type:"GET",
        dataType:"html",
        success:function(data){
            $("#my-modal").find(".modal-body").html(data);
            $("#my-modal").modal("show");
        }
        });
        });
    </script>
}

POS/POS.Web/Views/Order/_Add.cshtml
@model POS.ViewModel.OrderModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Order";
}
<h2>Add Order</h2>

<form asp-controller="Order" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CustomerId">Customer ID</label>
        <select type="text" asp-for="CustomerId" class="form-control" asp-items="@ViewBag.Customer">
            <option selected>Select Customer</option>
        </select>
        <span asp-validation-for="CustomerId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="EmployeeId">Employee ID</label>
       
        <select type="text" asp-for="EmployeeId" class="form-control" asp-items="@ViewBag.Employee">
            <option selected>Select Employee</option>
        </select>
        <span asp-validation-for="EmployeeId" class="text-danger" />
    </div> 

    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="OrderDate"></label>
        <input asp-for="OrderDate" class="form-control" type="date"/>
        <span asp-validation-for="OrderDate" class="text-danger" />
    </div>

    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="RequiredDate"></label>
        <input asp-for="RequiredDate" class="form-control" type="date"/>
        <span asp-validation-for="RequiredDate" class="text-danger" />
    </div>
    <div class="form-group date" id='datetimepicker4'>
        <label asp-for="ShippedDate"></label>
        <input asp-for="ShippedDate" class="form-control"  type="date"/>
        <span asp-validation-for="ShippedDate" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ShipVia"></label>
        <input asp-for="ShipVia" class="form-control" />
        <span asp-validation-for="ShipVia" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Freight"></label>
        <input asp-for="Freight" class="form-control" />
        <span asp-validation-for="Freight" class="text-danger" />
    </div>  
    <div class="form-group">
        <label asp-for="ShipName"></label>
        <input asp-for="ShipName" class="form-control" />
        <span asp-validation-for="ShipName" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipAddress"></label>
        <input asp-for="ShipAddress" class="form-control" />
        <span asp-validation-for="ShipAddress" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipCity"></label>
        <input asp-for="ShipCity" class="form-control" />
        <span asp-validation-for="ShipCity" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipRegion"></label>
        <input asp-for="ShipRegion" class="form-control" />
        <span asp-validation-for="ShipRegion" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipPostal"></label>
        <input asp-for="ShipPostal" class="form-control" />
        <span asp-validation-for="ShipPostal" class="text-danger" />
    </div>
  <div class="form-group">
        <label asp-for="ShipCountry"></label>
        <input asp-for="ShipCountry" class="form-control" />
        <span asp-validation-for="ShipCountry" class="text-danger" />
    </div>
  
    <h2 class="content-caption mb-0 d-flex justify-content-between">
        Order Detail
        <a class="btn-add add-detail" data-added="0"><i class="la la-plus la-lg">+</i></a>
    </h2>

    <table class="table table-borderless m-0" id="tbl_posts2">
        <thead>
            <tr>
                <th>Product ID</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Discount</th>
            </tr>
        </thead>
        <tbody id="tbl_posts_body2">
            <tr id="re-0">
                <td>
                    <select type="text" asp-for="OrderDetails[0].ProductId" class="form-control" asp-items="@ViewBag.Product">
                        <option selected>Select the Product</option>
                    </select>
                </td>
                <td><input asp-for="OrderDetails[0].Price" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Quantity" class="form-control" /></td>
                <td><input asp-for="OrderDetails[0].Discount" class="form-control" /></td>
                <td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td>
            </tr>

        </tbody>
        <tbody id="Detail-2">
        </tbody>

    </table>

    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

@*
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>*@



</form>

@section Scripts {
  <script type="text/javascript">
        $(document).ready(function () {

            //Education
            var j = 1;
            //added class to inputs
            $('a.add-detail').click(function () {
                $("#Detail-2").append('<tr><td><input id="OrderDetails_' + j + '__ProductId" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].ProductId" value=""/></td><td><input id="OrderDetails_' + j + '__Price" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Price" value=""/></td><td><input id="OrderDetails_' + j + '__Quantity" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Quantity" value=""/></td><td><input id="OrderDetails_' + j + '__Discount" class="form-control" type="text" data-val="true" name="OrderDetails[' + j + '].Discount" value=""/></td><td class="text-center"><a class="btn btn-xs delete-detail" edu-data-id="1"><i class="la la-trash la-lg text-danger">-</i></a></td></tr>');
                j++;
            });
            $('#Detail-2').on('click', '.delete-detail', function () {
                $(this).parent().parent().remove();
                j--; //decremnt count
                resetValues(); //call to reset values
            });

            function resetValues() {
                counter = 1; //initialze to 1
                //looping through tbody
                $("#Detail-2 tr").each(function () {
                    //find .school class replace its name value
                    $(this).find('.ProductId').attr("OrderDetails[" + counter + "].ProductId");
                    $(this).find('.Price').attr("OrderDetails[" + counter + "].Price");
                    $(this).find('.Quantity').attr("OrderDetails[" + counter + "].Quantity");
                    $(this).find('.Discount').attr("OrderDetails[" + counter + "].Discount");
                    counter++; //increment count
                })
            }
        });
    </script>

      
}