POS/POS.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly CustomerService _service;

        public CustomerController(AppDbContext context)
        {
            _service = new CustomerService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var data = _service.GetCustomer();
            return View(data);
        }

        [HttpGet]
        public  IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(CustomerModel request)
        {
            if (ModelState.IsValid)
            {
                _service.AddCustomer(new CustomerEntity(request));
                return Redirect("/Customer");
            }
            return View("Add", request);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var data = _service.DetailCustomer(id);
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(CustomerModel customer)
        {
            if (ModelState.IsValid)
            {
                _service.UpdateCustomer(customer);
                return Redirect("/Customer");
            }
            return View("Edit", customer);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.DeleteCustomer(id);
            return Redirect("/Customer");
        }
    }
}

POS/POS.Web/Views/Customer/Add.cshtml
@model POS.ViewModel.CustomerModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Customer";
}
<h2>Add Customer</h2>

<form asp-controller="Customer" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">s
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Customer/Details.cshtml
@model POS.Repository.CustomerEntity
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Detail Customer";
}
<h2>Detail Customer</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Company</th>
        <td>@Model.CompanyName</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>@Model.ContactName</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>@Model.ContactTitle</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <th>City</th>
        <td>@Model.City</td>
    </tr>
    <tr>
        <th>region</th>
        <td>@Model.region</td>
    </tr>
    <tr>
        <th>PostalCode</th>
        <td>@Model.PostalCode</td>
    </tr>
    <tr>
        <th>Country</th>
        <td>@Model.Country</td>
    </tr>
    <tr>
        <th>Phone</th>
        <td>@Model.Phone</td>
    </tr>
    <tr>
        <th>Fax</th>
        <td>@Model.Fax</td>
    </tr>
</table>

POS/POS.Web/Views/Customer/Edit.cshtml
@model POS.ViewModel.CustomerModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Customer";
}
<h2>Edit Customer</h2>
<form asp-controller="Customer" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
         <span asp-validation-for="CompanyName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
         <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactTitle"></label>
        <input asp-for="ContactTitle" class="form-control" />
         <span asp-validation-for="ContactTitle" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
         <span asp-validation-for="Address" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Customer/Index.cshtml
@model IEnumerable<POS.Repository.CustomerEntity>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Customer List";
}

<h2>Customers List</h2>
<a id="btn-add" class="btn btn-primary" asp-area="" asp-controller="Customer" asp-action="Add">Add Customer</a>
<table class="table table-responsive">
    <thead>
    <th>Id</th>
    <th>Company Name</th>
    <th>Name</th>
    <th>Title</th>
    <th>City</th>

    <th>Action</th>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
        <td>@item.Id</td>
        <td>@item.CompanyName</td>
        <td>@item.ContactName</td>
        <td>@item.ContactTitle</td>
        <td>@item.City</td>>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
        </td>
        </tbody>
    }
</table>

<div id="my-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#btn-add").on("click", function(e){
            e.preventDefault();
            $.ajax({
                url:"Customer/AddModal",
                type:"GET",
                dataType:"html",
                success: function(data){
                    $("#my-modal").find(".modal-body").html(data);
                    $("#my-modal").modal("show");
                }
            });
        });
    </script>
}

POS/POS.Web/Views/Customer/_Add.cshtml
@model POS.ViewModel.CustomerModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Customer";
}
<h2>Add Customer</h2>

<form asp-controller="Customer" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">s
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>

    <<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}