POS/POS.Web/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class SupplierController : Controller
    {
        private readonly SupplierService _service;

        public SupplierController(AppDbContext context)
        {
            _service = new SupplierService(context);
        }

        [HttpGet]
        public IActionResult Index()
        {
            var data = _service.GetSuppliers();
            return View(data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        } 
        public IActionResult AddModal()
        {
            return PartialView("_Add");
        }

        [HttpPost]
        public IActionResult Save(SupplierModel supplier)
        {
            if (ModelState.IsValid)
            {
                _service.AddSupplier(new SupplierEntity(supplier));
                return Redirect("/Supplier");
            }
            return View("Add", supplier);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var data = _service.DetailSupplier(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Update(SupplierModel supplier)
        {
            _service.UpdateSupplier(supplier);
            return Redirect("/Supplier");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.DeleteSupplier(id);
            return Redirect("/Supplier");
        }
    }
}

POS/POS.Web/Views/Supplier/Add.cshtml
@model POS.ViewModel.SupplierModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Supplier";
}
<h2>Add New Supplier</h2>

<form asp-controller="Supplier" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactTitle"></label>
        <input asp-for="ContactTitle" class="form-control" />
        <span asp-validation-for="ContactTitle" class="text-danger" />
    </div> 

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
        <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Homepage"></label>
        <input asp-for="Homepage" class="form-control" />
        <span asp-validation-for="Homepage" class="text-danger" />
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Supplier/Details.cshtml
@model POS.Repository.SupplierEntity
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Detail Supplier";
}
<h2>Detail Supplier</h2>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Company</th>
        <td>@Model.CompanyName</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>@Model.ContactName</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>@Model.ContactTitle</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <th>City</th>
        <td>@Model.City</td>
    </tr>
    <tr>
        <th>region</th>
        <td>@Model.region</td>
    </tr>
    <tr>
        <th>PostalCode</th>
        <td>@Model.PostalCode</td>
    </tr>
    <tr>
        <th>Country</th>
        <td>@Model.Country</td>
    </tr>
    <tr>
        <th>Phone</th>
        <td>@Model.Phone</td>
    </tr>
    <tr>
        <th>Fax</th>
        <td>@Model.Fax</td>
    </tr>
    <tr>
        <th>Homepage</th>
        <td>@Model.Homepage</td>
    </tr>
</table>

POS/POS.Web/Views/Supplier/Edit.cshtml
@model POS.ViewModel.SupplierModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Supplier";
}
<h2>Edit Supplier</h2>
<form asp-controller="Supplier" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactTitle"></label>
        <input asp-for="ContactTitle" class="form-control" />
                <span asp-validation-for="ContactTitle" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Homepage"></label>
        <input asp-for="Homepage" class="form-control" />
        <span asp-validation-for="Homepage" class="text-danger" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.Web/Views/Supplier/Index.cshtml
@model IEnumerable<POS.Repository.SupplierEntity>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Supplier List";
}

<h2>Suppliers List</h2>
<a class="btn btn-primary" asp-area="" asp-controller="Supplier" asp-action="Add">Add Supplier</a>
<table class="table table-responsive">
    <thead>
    <th>Id</th>
    <th>Company Name</th>
    <th>Contact Name</th>
    <th>Contact Title</th>
    <th>Action</th>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
        <td>@item.Id</td>
        <td>@item.CompanyName</td>
        <td>@item.ContactName</td>
        <td>@item.ContactTitle</td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
        </td>
        </tbody>
    }
</table>

<div id="my-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>

@section Scripts{
<script type="text/javascript">
    $("#btn-add").on("click", function(e){
        e.preventDefault();
        $.ajax({
        url:"Supplier/AddModal",
        type:"GET",
        dataType:"html",
        success: function(data){
            $("#my-modal").find(".modal-body").html(data);
            $("#my-modal").modal("show");
        }
        });
    });
</script>
}

POS/POS.Web/Views/Supplier/_Add.cshtml
@model POS.ViewModel.SupplierModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Supplier";
}
<h2>Add New Supplier</h2>

<form asp-controller="Supplier" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactTitle"></label>
        <input asp-for="ContactTitle" class="form-control" />
        <span asp-validation-for="ContactTitle" class="text-danger" />
    </div> 

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>

    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="region"></label>
        <input asp-for="region" class="form-control" />
        <span asp-validation-for="region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
        <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Homepage"></label>
        <input asp-for="Homepage" class="form-control" />
        <span asp-validation-for="Homepage" class="text-danger" />
    </div>

    <<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}